#!/bin/bash

for file in `ls tests/ | grep in | cut -d"." -f1`; do
	echo Running test for $file
	./hw5 < tests/${file}.in > tests/${file}.llvm
   lli < tests/${file}.llvm > tests/${file}.res
	diff tests/$file.res tests/${file}.out
 	if [[ $? != 0 ]] 
		then
		echo "Failed test #"$i"!" 
    break
	else
	  echo "Test "$i" passed!"
  fi  
	echo \*\*\* DONE \*\*\*
done
